//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportAgahPriceHistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSecurityHistory
    {
        public int SecurityID { get; set; }
        public int SecurityHistoryID { get; set; }
        public string SecuritySymbol { get; set; }
        public string SecurityName { get; set; }
        public string SecurityDescription { get; set; }
        public System.DateTime Date { get; set; }
        public string DatePersian { get; set; }
        public double ClosingPrice { get; set; }
        public Nullable<double> VolumeWeightedPrice { get; set; }
        public double OpeningPrice { get; set; }
        public double HighestPrice { get; set; }
        public double LowestPrice { get; set; }
        public long Volume { get; set; }
        public string AdjustmentType { get; set; }
        public int AdjustmentTypeID { get; set; }
        public int MarketTypeID { get; set; }
        public int SecurityTypeID { get; set; }
        public Nullable<int> AgahID { get; set; }
        public Nullable<int> AgahSecurityID { get; set; }
        public long TseID { get; set; }
        public string SecurityType { get; set; }
        public string MarketType { get; set; }
        public Nullable<int> NaturalBuyCount { get; set; }
        public Nullable<int> LegalBuyCount { get; set; }
        public Nullable<int> NaturalSellCount { get; set; }
        public Nullable<int> LegalSellCount { get; set; }
        public Nullable<long> NaturalBuyVolume { get; set; }
        public Nullable<long> LegalBuyVolume { get; set; }
        public Nullable<long> NaturalSellVolume { get; set; }
        public Nullable<long> LegalSellVolume { get; set; }
        public int SecurityGroupID { get; set; }
        public string SecurityGroupTitle { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusDescription { get; set; }
        public int Rahavard365ID { get; set; }
        public long SharesCount { get; set; }
        public int EPS { get; set; }
        public long BaseVolume { get; set; }
        public Nullable<double> BuyerStrength { get; set; }
        public Nullable<double> VolumeStrength { get; set; }
        public Nullable<double> ClosingPricePercentChange { get; set; }
        public Nullable<double> VolumeWeightedPricePercentChange { get; set; }
    }
}
